(deftheme Venturemacs-dark
  "Venturemacs dark theme")

(custom-theme-set-variables
 'Venturemacs-dark
 '(ansi-color-names-vector ["#1A1A1A" "#C67878" "#88B088" "#C5A37E" "#8197BF" "#B181B1" "#8BA4B1" "#CCCCCC"]))

(custom-theme-set-faces
 'Venturemacs-dark
 '(default ((t (:background "#1A1A1A" :foreground "#CCCCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#8BA4B1"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#666666"))))
 '(font-lock-comment-face ((t (:foreground "#666666" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#B181B1"))))
 '(font-lock-doc-face ((t (:foreground "#666666"))))
 '(font-lock-function-name-face ((t (:foreground "#C67878"))))
 '(font-lock-keyword-face ((t (:foreground "#B181B1"))))
 '(font-lock-negation-char-face ((t (:foreground "#C5A37E" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#8BA4B1"))))
 '(font-lock-string-face ((t (:foreground "#88B088"))))
 '(font-lock-type-face ((t (:foreground "#C5A37E"))))
 '(font-lock-variable-name-face ((t (:foreground "#CCCCCC"))))
 '(font-lock-warning-face ((t (:foreground "#D08770" :weight bold :underline t))))
 '(button ((t (:underline t))))
 '(highlight ((t (:background "#2A2A2A"))))
 '(region ((t (:background "#3E4451" :foreground "#FFFFFF"))))
 '(cursor ((t (:background "#CCCCCC" :foreground "#1A1A1A"))))
 '(fringe ((t (:background "#1A1A1A" :foreground "#444444"))))
 '(line-number ((t (:foreground "#4B5263" :background "#1A1A1A"))))
 '(line-number-current-line ((t (:foreground "#CCCCCC" :background "#2A2A2A" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#B181B1" :weight bold))))
 '(mode-line ((t (:foreground "#CCCCCC" :background "#2A2A2A" :box (:line-width 1 :color "#444444")))))
 '(mode-line-inactive ((t (:foreground "#666666" :background "#1E1E1E" :box (:line-width 1 :color "#2A2A2A")))))
 '(header-line ((t (:inherit mode-line))))
 '(vertical-border ((t (:foreground "#2A2A2A"))))
 '(link ((t (:foreground "#8197BF" :underline t))))
 '(error ((t (:foreground "#C67878" :weight bold))))
 '(warning ((t (:foreground "#C5A37E" :weight bold))))
 '(success ((t (:foreground "#88B088" :weight bold))))
 '(compilation-error ((t (:inherit error))))
 '(compilation-info ((t (:foreground "#8BA4B1" :weight bold))))
 '(vertico-current ((t (:background "#2A2A2A" :foreground "#CCCCCC" :weight bold))))
 '(completions-common-part ((t (:foreground "#8BA4B1"))))
 '(completions-first-difference ((t (:foreground "#B181B1" :weight bold))))
 '(company-tooltip ((t (:background "#1E1E1E" :foreground "#CCCCCC"))))
 '(company-tooltip-selection ((t (:background "#2A2A2A" :foreground "#CCCCCC" :weight bold))))
 '(company-scrollbar-bg ((t (:background "#1A1A1A"))))
 '(company-scrollbar-fg ((t (:background "#444444"))))
 '(eglot-highlight-face ((t (:inherit highlight :underline t))))
 '(magit-section-highlight ((t (:background "#2A2A2A"))))
 '(magit-diff-added ((t (:foreground "#88B088" :background "#1E271E"))))
 '(magit-diff-added-highlight ((t (:foreground "#88B088" :background "#2A3628"))))
 '(magit-diff-removed ((t (:foreground "#C67878" :background "#2D1E1E"))))
 '(magit-diff-removed-highlight ((t (:foreground "#C67878" :background "#3F2828"))))
 '(magit-hash ((t (:foreground "#666666"))))
 '(org-level-1 ((t (:foreground "#CCCCCC" :weight bold :height 1.2))))
 '(org-level-2 ((t (:foreground "#B181B1" :weight bold :height 1.1))))
 '(org-level-3 ((t (:foreground "#8BA4B1" :weight bold))))
 '(org-link ((t (:foreground "#8197BF" :underline t))))
 '(org-todo ((t (:foreground "#C67878" :weight bold))))
 '(org-done ((t (:foreground "#88B088" :weight bold))))
 '(show-paren-match ((t (:background "#444444" :foreground "#CCCCCC" :weight bold))))
 '(dashboard-heading ((t (:foreground "#CCCCCC" :weight bold))))
 '(dashboard-banner-logo-title ((t (:foreground "#B181B1" :weight bold))))
 '(which-key-key-face ((t (:foreground "#B181B1" :weight bold))))
 '(which-key-group-description-face ((t (:foreground "#8BA4B1"))))
 '(which-key-command-description-face ((t (:foreground "#CCCCCC"))))
 '(web-mode-html-tag-face ((t (:foreground "#B181B1"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#C67878"))))
 '(web-mode-html-attr-value-face ((t (:foreground "#88B088")))))

(provide-theme 'Venturemacs-dark)
