(deftheme Venturemacs-light
  "Venturemacs light theme")

(custom-theme-set-variables
 'Venturemacs-light
 '(ansi-color-names-vector ["#1A1A1A" "#A54A4A" "#3A5A3A" "#8B6B4A" "#3A4A6A" "#5A3A5A" "#3A4A5A" "#CCCCCC"]))

(custom-theme-set-faces
 'Venturemacs-light
 '(default ((t (:background "#F5F5F5" :foreground "#1A1A1A"))))
 '(font-lock-builtin-face ((t (:foreground "#3A4A5A"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7A7A7A"))))
 '(font-lock-comment-face ((t (:foreground "#757575" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#4A3A5A"))))
 '(font-lock-doc-face ((t (:foreground "#7A7A7A"))))
 '(font-lock-function-name-face ((t (:foreground "#C62828"))))
 '(font-lock-keyword-face ((t (:foreground "#7B1FA2"))))
 '(font-lock-negation-char-face ((t (:foreground "#8B6B4A" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#3A4A5A"))))
 '(font-lock-string-face ((t (:foreground "#2E7D32"))))
 '(font-lock-type-face ((t (:foreground "#8B6B4A"))))
 '(font-lock-variable-name-face ((t (:foreground "#1A1A1A"))))
 '(font-lock-warning-face ((t (:foreground "#A5522A" :weight bold :underline t))))
 '(button ((t (:underline t))))
 '(highlight ((t (:background "#BBBBBB"))))
 '(region ((t (:background "#A0A0A0" :foreground "#000000"))))
 '(cursor ((t (:background "#1A1A1A" :foreground "#CCCCCC"))))
 '(fringe ((t (:background "#F5F5F5" :foreground "#999999"))))
 '(line-number ((t (:foreground "#999999" :background "#FAFAFA"))))
 '(line-number-current-line ((t (:foreground "#000000" :background "#E0E8F0" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#5A3A5A" :weight bold))))
 '(mode-line ((t (:foreground "#1A1A1A" :background "#D2D2D2" :box (:line-width 1 :color "#B0B0B0")))))
 '(mode-line-inactive ((t (:foreground "#666666" :background "#C8C8C8" :box (:line-width 1 :color "#B0B0B0")))))
 '(header-line ((t (:inherit mode-line))))
 '(vertical-border ((t (:foreground "#CCCCCC"))))
 '(link ((t (:foreground "#3A4A6A" :underline t))))
 '(error ((t (:foreground "#A54A4A" :weight bold))))
 '(warning ((t (:foreground "#8B6B4A" :weight bold))))
 '(success ((t (:foreground "#3A5A3A" :weight bold))))
 '(compilation-error ((t (:inherit error))))
 '(compilation-info ((t (:foreground "#3A4A5A" :weight bold))))
 '(vertico-current ((t (:background "#C0C0C0" :foreground "#1A1A1A" :weight bold))))
 '(completions-common-part ((t (:foreground "#3A4A5A"))))
 '(completions-first-difference ((t (:foreground "#5A3A5A" :weight bold))))
 '(company-tooltip ((t (:background "#E6E6E6" :foreground "#1A1A1A"))))
 '(company-tooltip-selection ((t (:background "#C0C0C0" :foreground "#1A1A1A" :weight bold))))
 '(company-scrollbar-bg ((t (:background "#CCCCCC"))))
 '(company-scrollbar-fg ((t (:background "#AAAAAA"))))
 '(eglot-highlight-face ((t (:inherit highlight :underline t))))
 '(magit-section-highlight ((t (:background "#C0C0C0"))))
 '(magit-diff-added ((t (:foreground "#3A5A3A" :background "#D8E2D8"))))
 '(magit-diff-added-highlight ((t (:foreground "#3A5A3A" :background "#CAD4CA"))))
 '(magit-diff-removed ((t (:foreground "#A54A4A" :background "#E0D0D0"))))
 '(magit-diff-removed-highlight ((t (:foreground "#A54A4A" :background "#D2C2C2"))))
 '(magit-hash ((t (:foreground "#888888"))))
 '(org-level-1 ((t (:foreground "#1A1A1A" :weight bold :height 1.2))))
 '(org-level-2 ((t (:foreground "#4A3A5A" :weight bold :height 1.1))))
 '(org-level-3 ((t (:foreground "#3A4A5A" :weight bold))))
 '(org-link ((t (:foreground "#3A4A6A" :underline t))))
 '(org-todo ((t (:foreground "#A54A4A" :weight bold))))
 '(org-done ((t (:foreground "#3A5A3A" :weight bold))))
 '(show-paren-match ((t (:background "#B0B0B0" :foreground "#1A1A1A" :weight bold))))
 '(dashboard-heading ((t (:foreground "#1A1A1A" :weight bold))))
 '(dashboard-banner-logo-title ((t (:foreground "#5A3A5A" :weight bold))))
 '(which-key-key-face ((t (:foreground "#5A3A5A" :weight bold))))
 '(which-key-group-description-face ((t (:foreground "#3A4A5A"))))
 '(which-key-command-description-face ((t (:foreground "#1A1A1A"))))
 '(web-mode-html-tag-face ((t (:foreground "#7B1FA2"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#C62828"))))
 '(web-mode-html-attr-value-face ((t (:foreground "#2E7D32")))))

(provide-theme 'Venturemacs-light)
